# Generated by Django 5.1.1 on 2024-09-10 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_product_delete_moodentry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
